/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class GiftIdeaModule extends AbstractGiftIdeaModule {
}
