/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.idea.completion

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage
import org.xtext.example.mydsl.idea.lang.GiftLanguage

class GiftCompletionContributor extends AbstractGiftCompletionContributor {
	new() {
		this(GiftLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
