/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.idea.lang


class GiftFileType extends AbstractGiftFileType {
	public static final GiftFileType INSTANCE = new GiftFileType()
	
	new() {
		super(GiftLanguage.INSTANCE)
	}
}
