/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GiftStandaloneSetup extends GiftStandaloneSetupGenerated {

	def static void doSetup() {
		new GiftStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
